<b>Задание 1</b><br>
Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
<br>
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
<br>
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
<br>
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [28]:
import numpy as np

# see docs: https://numpy.org/doc/stable/reference/generated/numpy.cov.html#numpy.cov
# https://stackoverflow.com/questions/15317822/calculating-covariance-with-python-and-numpy
# https://numpy.org/doc/stable/reference/generated/numpy.var.html

zp= [35, 45, 190, 200, 40, 70, 54, 150, 120, 110];
ks =  [401, 574, 874, 919, 459, 739, 653, 902, 746, 832];

zp_ks = np.stack((zp, ks), axis=0)
print ("  --> stacked: \n{}\n".format(zp_ks))
cov_x_matrix=np.cov(zp_ks);
print ("  --> covariance matrix: \n{}\n".format(cov_x_matrix))


# see article: https://kpfu.ru/portal/docs/F_2064674290/NPS_19.Pirson.Menshov.pdf
# https://www.codecamp.ru/blog/pearson-correlation-coefficient/
cov_zp_ks = cov_x_matrix[0][1]
zp_variance = np.var(zp) ** 0.5
ks_variance = np.var(ks) ** 0.5
pirson_corr = cov_zp_ks/(zp_variance*ks_variance);

print ("Pirson coefficient = {}".format(pirson_corr))


  --> stacked: 
[[ 35  45 190 200  40  70  54 150 120 110]
 [401 574 874 919 459 739 653 902 746 832]]

  --> covariance matrix: 
[[ 3882.93333333 10175.37777778]
 [10175.37777778 33854.32222222]]

0.9861001023043511


In [24]:
# The standard corr-coef has different result because it doesn't use the variance
# https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

pirson_corr_coeff_matrix = np.corrcoef(zp,ks)
pirson_corr_coeff_matrix

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [31]:
# The basic formula:

zp = np.array(zp)
zp_average = np.average(zp)
zp_a = zp-zp_average

ks = np.array(ks)
ks_average = np.average(ks)
ks_a = ks-ks_average

pirson_coefficient=np.correlate(zp_a,ks_a)/((np.var(ks_a) ** 0.5) * (np.var(zp_a) ** 0.5))

print ("Pirson coefficient = {}".format(pirson_corr))



Pirson coefficient = 0.9861001023043511


<b>Задание 2</b></br>
Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [33]:
import scipy.stats as stat

X = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111]);
t1,t2 = stat.t.interval(alpha=0.95, df=X.size-1, loc=np.average(X), scale=stat.sem(X))

print ("t1={}, t2={}".format(t1,t2))

t1=110.55608365158724, t2=125.64391634841274


<b>Задание 3</b>
<br>
Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [34]:
t1,t2 = stat.t.interval(alpha=0.95, df=27-1, loc=174.2, scale=25)
print ("t1={}, t2={}".format(t1,t2))

t1=122.81176403392823, t2=225.58823596607175
